import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/toaster";
import Sidebar from "@/components/Sidebar/Sidebar";

const inter = Montserrat({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "John CEO",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} `}>
        <div className="flex overflow-hidden h-screen">
          <aside>
            <Sidebar />
          </aside>
          <main className="bg-[#F1F4F6] h-screen w-full overflow-y-auto px-10 py-5">
            {children}
          </main>
        </div>
        <Toaster />
      </body>
    </html>
  );
}
